version: '3.7'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data/mysql:/var/lib/mysql
      - ./mysql-init.d:/docker-entrypoint-initdb.d
    restart: always
    env_file:
      ./env/.mysql-env
    networks:
       - overlay
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
## Site 1 
  site1_wp:
    image: wordpress:5-fpm
    volumes:
       - ./php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
       - ./site1/wp:/var/www/html
    env_file:
      ./site1/.wp-env
    depends_on:
      - db
    restart: always
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
  site1_nginx:
    image: nginx
    depends_on:
      - site1_wp
    volumes:
      - ./site1/wp:/var/www/html
      - ./site1/nginx:/etc/nginx/conf.d
    restart: always
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
  certbot1:
    depends_on:
      - site1_nginx
    image: certbot/certbot
    volumes:
      - ./certbot1-etc:/etc/letsencrypt
      - ./certbot1-var:/var/lib/letsencrypt
      - ./site1/wp:/var/www/html
      - ./logs/site1/certbot:/var/log
### Un-comment below line after testing for actual certificate generation
#    command: certonly --webroot --webroot-path=/var/www/html --email youremail@abc.com --agree-tos --no-eff-email -d www.example1.com
### comment below line after initial testing
    command: certonly --webroot --staging --webroot-path=/var/www/html --email youremail@abc.com --agree-tos --no-eff-email -d www.example1.com
### Un-comment below line after actual cert generation for renewal
#    command: renew --dry-run
    networks:
      - overlay
## Site 2
  site2_wp:
    image: wordpress:5-fpm
    volumes:
      - ./php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./site2/wp:/var/www/html
    env_file:
      ./site2/.wp-env
    depends_on:
      - db
    restart: always
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
  site2_nginx:
    image: nginx
    depends_on:
      - site2_wp
    volumes:
      - ./site2/wp:/var/www/html
      - ./site2/nginx:/etc/nginx/conf.d
    restart: always
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
  certbot2:
    depends_on:
      - site2_nginx
    image: certbot/certbot
    volumes:
      - ./certbot2-etc:/etc/letsencrypt
      - ./certbot2-var:/var/lib/letsencrypt
      - ./site2/wp:/var/www/html
      - ./logs/site2/certbot:/var/log
### Un-comment after testing for actual certificate generation
#    command: certonly --webroot --webroot-path=/var/www/html --email youremail@abc.com --agree-tos --force-renewal --no-eff-email -d www.example2.com
### comment below after initial testing
    command: certonly --webroot --staging --webroot-path=/var/www/html --email youremail@abc.com --agree-tos --no-eff-email -d www.example2.com
### Un-comment after actual cert generation for renewal
#    command: renew --dry-run
    networks:
      - overlay
## Common nginx
  nginx:
    image: nginx
    depends_on:
      - site1_nginx
      - site2_nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./certbot:/var/www/html
      - ./certbot1-etc:/etc/letsencrypt1
      - ./certbot2-etc:/etc/letsencrypt2
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
## Phpmyadmin for easy DB management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_AUTH_TYPE: cookie
    networks:
       - overlay
networks:
  overlay:
