CREATE DATABASE IF NOT EXISTS wp_site1;
CREATE USER 'wp_user_site1'@'%' IDENTIFIED BY 'z2&NWU7Kxk3SW^R';
GRANT USAGE ON *.* TO 'wp_user_site1'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `wp_site1`.* TO 'wp_user_site1'@'%';

CREATE DATABASE IF NOT EXISTS wp_site2;
CREATE USER 'wp_user_site2'@'%' IDENTIFIED BY 'fsdyx@xrEa9HK0H';
GRANT USAGE ON *.* TO 'wp_user_site2'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `wp_site2`.* TO 'wp_user_site2'@'%';